### ISSUE TITLE
Guid type Id problem

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#138]
Can't .Delete() items that have Guid as ID.

Sample to reproduce this problem, first SQL to create a table and a row:

        CREATE TABLE [dbo].[TestMessage](
           [Id] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Appointment_Id]  DEFAULT (newsequentialid()),
           [MessageText] [text] NOT NULL,
         CONSTRAINT [PK_TestMessage] PRIMARY KEY CLUSTERED (
           [Id] ASC
         )WITH (
           PAD_INDEX = OFF, 
           STATISTICS_NORECOMPUTE = OFF, 
           IGNORE_DUP_KEY = OFF, 
           ALLOW_ROW_LOCKS = ON, 
           ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
           ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
           GO

        INSERT INTO [dbo].[TestMessage] ([Id],[MessageText]) 
        VALUES ('6A53C06C-D914-4972-A449-1176051CB3FE','Hello')
        GO

If ``CONSTRAINT [DF_Appointment_Id]  DEFAULT (newsequentialid())`` is left away, then Insert() fails also, but this way it works. But Delete() fails anyway. Sample the F#-code:

        #r @"./packages/SQLProvider/lib/net40/FSharp.Data.SqlProvider.dll"
        open System
        open System.Linq
        open FSharp.Data.Sql

        type SqlConnection = 
            SqlDataProvider<
                ConnectionString = @"Data Source=localhost; Initial Catalog=mydatabase; Integrated Security=True;",
                DatabaseVendor = Common.DatabaseProviderTypes.MSSQLSERVER,
                UseOptionTypes = true>
        let context = SqlConnection.GetDataContext()
        context.``[dbo].[TestMessage]``.First().Delete()        
        context.SubmitUpdates()

fails with:

        System.InvalidCastException: Object must implement IConvertible.
           at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
           at System.Convert.ChangeType(Object value, Type conversionType)
           at FSharp.Data.Sql.Common.SqlEntity.GetColumnOption[T](String key) in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.Common.fs:line 89
        >    at <StartupCode$FSharp-Data-SqlProvider>.$Providers.MsSqlServer.createDeleteCommand@493.Invoke(SqlEntity entity) in F:\GIT\SQLProvider\src\SQLProvider\Providers.MsSqlServer.fs:line 499
           at <StartupCode$FSharp-Data-SqlProvider>.$Providers.MsSqlServer.FSharp-Data-Sql-Common-ISqlProvider-ProcessUpdates@512-2.Invoke(SqlEntity e) in F:\GIT\SQLProvider\src\SQLProvider\Providers.MsSqlServer.fs:line 530
           at Microsoft.FSharp.Primitives.Basics.List.iter[T](FSharpFunc`2 f, FSharpList`1 x)
           at Microsoft.FSharp.Collections.ListModule.Iterate[T](FSharpFunc`2 action, FSharpList`1 list)
           at FSharp.Data.Sql.Providers.MSSqlServerProvider.FSharp-Data-Sql-Common-ISqlProvider-ProcessUpdates(IDbConnection con, FSharpList`1 entities) in F:\GIT\SQLProvider\src\SQLProvider\Providers.MsSqlServer.fs:line 511
           at FSharp.Data.Sql.Runtime.SqlDataContext.FSharp-Data-Sql-Common-ISqlDataContext-SubmitPendingChanges() in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.DataContext.fs:line 38

**Comment by Thorium** [comment]
This seems to be issue in the NuGet-package version, but not anymore in GitHub-source-code-version.
