### ISSUE TITLE
Joining with multiple keys

### ISSUE THREAD

**Issue by colinbull** [fsprojects/SQLProvider#141]
On lots of databases the relationships aren't explict thus the `GetSchema` call doesn't pick things up. So we can't use the relationship navigation properties that the provider supplies. To get around this you need to create an explict join. This works nicely for a single key but when you have to join on multiple keys it doesn't work. For example, 

```
query {
    for price in ctx.Dbo.Price do
    join commodityMarket in ctx.Dbo.CommodityMarket on (price.CommktKey = commodityMarket.CommktKey)
    join tradingPeriod in ctx.Dbo.TradingPeriod on ((price.TradingPrd, price.CommktKey) = (tradingPeriod.TradingPrd, tradingPeriod.CommktKey))
    join commodity in ctx.Dbo.Commodity on (commodityMarket.CmdtyCode = commodity.CmdtyCode)
    where (price.PriceQuoteDate >= quoteDate 
        && tradingPeriod.TradingPrd <> "SPOT"
        && price.PriceSourceCode = "INTERNAL"
        && commodity.CmdtyType = "P"
        && commodityMarket.MktCode <>% "OSP%")
    select (price.PriceQuoteDate, 
            commodityMarket.MktCode,
            commodityMarket.CmdtyCode,
            tradingPeriod.FirstDelDate,
            tradingPeriod.LastDelDate,
            price.AvgClosedPrice,
            tradingPeriod.TradingPrd)

} 
```

However, currently this doesn't work yielding the following error. 

```
System.Exception
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1737-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at FSI_0003.Lacima.Loader.Symphony.getPrices(DateTime quoteDate) in C:\Appdev\lacima loader\Lacima.Loader\Lacima.Loader\Symphony.fs:line 16
   at <StartupCode$FSI_0005>.$FSI_0005.main@() in C:\Appdev\lacima loader\Lacima.Loader\Lacima.Loader\Script.fsx:line 23
Stopped due to error
```

**Comment by Thorium** [comment]
The first version is now implemented...

**Comment by tforkmann** [comment]
Hi there,
is the multi-table-multi-key-joins now supported?

Or is there a workaround for this?

**Comment by tforkmann** [comment]
Ok,

i just tested the join with multiple keys like mentioned before.
It works smoothly!
Thank you for that implementation!

**Comment by Thorium** [comment]
Yes, this is supported.

**Comment by nojaf** [comment]
I seem to be having a bug with this in MySql. 
I'm trying:

```fsharp
                query {
                    for t in sdrContext.Sdr2016.Team do
                    for p in t.``sdr2016.profile by team_id`` do
                    for u in p.``sdr2016.user by user_id``do
                    for bu in u.``sdr2016.brand_user by user_id`` do
                    for pj in t.``sdr2016.project by project_id`` do
                    join b in sdrContext.Sdr2016.Brand on (( pj.BrandId.Value, bu.BrandId) = (b.Id, b.Id))
                    where (p.Status = "completed" && projectIds.Contains(pj.Id))
                    select ({ Id = t.Id; TeamNr = t.Teamnr; Name = t.Name; FbId = bu.FacebookId })
                }
```

The printed SQL;
```sql
SET @param1 = 'completed';
SET @param2 = 48;
SELECT `arg1`.`id` as '`arg1`.`id`',`arg1`.`teamnr` as '`arg1`.`teamnr`',`arg1`.`name` as '`arg1`.`name`',`arg4`.`facebook_id` as '`arg4`.`facebook_id`' 
FROM sdr2016.team as `arg1` 
  INNER JOIN  `sdr2016`.`profile` as `arg2` on `arg1`.`id` = `arg2`.`team_id`
  INNER JOIN  `sdr2016`.`user` as `arg3` on `arg3`.`id` = `arg2`.`user_id`
INNER JOIN  `sdr2016`.`brand_user` as `arg4` on `arg3`.`id` = `arg4`.`user_id`
INNER JOIN  `sdr2016`.`project` as `pj` on `pj`.`id` = `arg1`.`project_id`
  INNER JOIN  `sdr2016`.`brand` as `b` on `pj`.`brand_id` = `b`.`id` AND `pj`.`brand_id` = `b`.`id`
WHERE ((`arg2`.`status` = @param1 AND `pj`.`id` IN (@param2))) -- params @param1 - "completed"; @param2 - 48; 
```

It seems to be duplicating the first part. Or am I missing something here?

**Comment by Thorium** [comment]
Does the same happen if you do explicit joins? I.e. something like:

```fsharp
query {
	for t in sdrContext.Sdr2016.Team do
	for p in t.``sdr2016.profile by team_id`` do
	for u in p.``sdr2016.user by user_id``do
	join bu in sdrContext.Sdr2016.BrandUser on (u.Id=bu.UserId)
	join pj in sdrContext.Sdr2016.Project on (t.ProjectId=pj.Id)
	join b in sdrContext.Sdr2016.Brand on (( pj.BrandId.Value, bu.BrandId) = (b.Id, b.Id))
	where (p.Status = "completed" && projectIds.Contains(pj.Id))
	select ({ Id = t.Id; TeamNr = t.Teamnr; Name = t.Name; FbId = bu.FacebookId })
}
```

**Comment by nojaf** [comment]
@Thorium same result I'm afraid.

**Comment by Thorium** [comment]
Ok, reading my previous comment, it actually states `Don't support multi-table-multi-key-joins`.

**Comment by nojaf** [comment]
So now I'm confused, whats https://github.com/fsprojects/SQLProvider/pull/318 then?

**Comment by Thorium** [comment]
This should work:
```fsharp
for x in xs do
join y in ys on ((x.id, x.year) = (y.id, y.year))
```

This should also work:
```fsharp
for x in xs do
join y in ys on ((x.id, x.year) = (y.id, y.year+1))
```

But this needs more work:
```fsharp
for a in as do
join b in bs on (a.id=5)
join c in cs on ((a.id, b.id) = (c.aid, c.bid))
```

**Comment by nojaf** [comment]
Ah I see, thx for the explainer.

**Comment by 64J0** [comment]
From this example I understood that it works like an `and`:

```fsharp
for a in as do
join b in bs on (a.id=5)
join c in cs on ((a.id, b.id) = (c.aid, c.bid))
```

Does it support the `or` too?

**Comment by 64J0** [comment]
I decided to open a new issue since this one was already closed.
