### ISSUE TITLE
unrecognised method call for basic query

### ISSUE THREAD

**Issue by jamessdixon** [fsprojects/SQLProvider#176]
I am running this query against AdventureWorks:

let salesOrderQuery = query { for soh in context.Sales.SalesOrderHeader do
                              join sod in context.Sales.SalesOrderDetail on (soh.SalesOrderId = sod.SalesOrderId)
                              join p in context.Production.Product on (sod.ProductId = p.ProductId)
                              where (soh.OrderDate > DateTime(2013,5,1))
                              groupBy soh.SalesOrderId into so
                              select(so)} |> Seq.toArray

And I am getting this error
System.Exception: unrecognised method call
   at Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.EvaluateQuotation(FSharpExpr e)
>    at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedInner(CanEliminate canElim, FSharpExpr queryProducingSequence)
   at Microsoft.FSharp.Linq.QueryModule.EvalNonNestedOuter(CanEliminate canElim, FSharpExpr tm)
   at Microsoft.FSharp.Linq.QueryModule.clo@1735-1.Microsoft-FSharp-Linq-ForwardDeclarations-IQueryMethods-Execute[a,b](FSharpExpr`1 )
   at <StartupCode$FSI_0003>.$FSI_0003.main@() in

**Comment by jamessdixon** [comment]
Never mind.  It is ithe groupBy clause.  Sorry to bother,

**Comment by pezipink** [comment]
feel free to implement groupby! :D

**Comment by jamessdixon** [comment]
IKR!

**Comment by Thorium** [comment]
Done. This works now. :-P
