### ISSUE TITLE
Best practices for SqlDataProvider type constructor resolution path?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SQLProvider#193]
I managed to create source code that actually works for both .NET and Mono:

        [<Literal>]
        let Mysqldatapath = __SOURCE_DIRECTORY__ + @"/../packages/MySql.Data/lib/net45/"
        type TypeProviderConnection = 
            SqlDataProvider<
                ConnectionString = @"...",
                DatabaseVendor = Common.DatabaseProviderTypes.MYSQL,
                IndividualsAmount=1000,
                UseOptionTypes=true, 
                Owner="mydatabase",
                ResolutionPath=Mysqldatapath>

Now this works in development ok, Intellisense is working fine. Also development runtime is working fine. And this works also in F# Interactive!

But then I compile this to exe and copy it away to some another machine with the dlls needed (like `FSharp.Data.SqlProvider.dll` and `MySql.Data.dll`). What happens it that it fails on runtime to not find the MySql.Data.dll from path `C:\git\myproject\packages\MySql.Data\lib\net45\MySql.Data.dll`. That is not a surprise as the file is not in there (which was compile time `__SOURCE_DIRECTORY__`) but it is in the same path as the actual executable.

So could the ResolutionPath be changed to search also the current directory first and not to fail when this compile-time-path is not there?

Or is there better way to reference resolution-path from the NuGet package so that .Net and Mono would still work in all these cases? The possibilities are quite limited as this is literal constant and so there can't be any string manipulation or usage of `System.IO.Path.DirectorySeparatorChar` (Windows vs. Mac/Unix) or `System.Environment.CurrentDirectory`. And F# interactive runtime directory is somethin weird, not the project's path. (In Windows it is AppData\Local\Temp)

The exception of the runtime is this:

		Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationExcept
		ion: The type initializer for 'OwinStart' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$myproject>.$OwinStar
		t' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Domain' threw an exception. ---> System.TypeInitializationException: T
		he type initializer for '<StartupCode$myproject>.$Domain' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\gi
		t\myproject\packages\MySql.Data\lib\net45\MySql.Data.dll' or one of its dependencies. The system cannot find the file specified.
		   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
		stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
		   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
		k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
		   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
		k& stackMark, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
		   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm,
		Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
		   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
		   at FSharp.Data.Sql.Providers.MySqlProvider..ctor(String resolutionPath) in F:\GIT\SQLProvider\src\SQLProvider\Providers.MySql.fs:line 28
		   at FSharp.Data.Sql.Common.Utilities.createSqlProvider(DatabaseProviderTypes vendor, String resolutionPath, String owner) in F:\GIT\SQLProvider\src\SQLProvide
		r\SqlRuntime.QueryExpression.fs:line 11
		   at <StartupCode$FSharp-Data-SqlProvider>.$SqlRuntime.DataContext.-ctor@15-54.Invoke(Unit unitVar0) in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.DataConte
		xt.fs:line 19
		   at FSharp.Data.Sql.Runtime.SqlDataContext..ctor(String typeName, String connectionString, DatabaseProviderTypes providerType, String resolutionPath, String o
		wner) in F:\GIT\SQLProvider\src\SQLProvider\SqlRuntime.DataContext.fs:line 15
		   at <StartupCode$myproject>.$Domain..cctor() in C:\git\myproject\backend\Domain.fs:line 32
		   --- End of inner exception stack trace ---
		   at Domain..cctor() in C:\git\myproject\backend\Domain.fs:line 0
		   --- End of inner exception stack trace ---
		   at Domain.getRootedPath(String path)
		   at <StartupCode$myproject>.$OwinStart..cctor() in C:\git\myproject\backend\OwinStartup.fs:line 29
		   --- End of inner exception stack trace ---
		   at OwinStart..cctor() in C:\git\myproject\backend\OwinStartup.fs:line 0
		   --- End of inner exception stack trace ---
		   at OwinStart.get_hubConfig()
		   at OwinStart.MyWebStartup.Configuration(IAppBuilder ap) in C:\git\myproject\backend\OwinStartup.fs:line 283
		   --- End of inner exception stack trace ---
		   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
		   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
		   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
		   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
		   at Owin.Loader.DefaultLoader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder)
		   at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
		   at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
		   at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
		   at myproject.main(String[] args) in C:\git\myproject\backend\Program.fs:line 49

**Comment by pezipink** [comment]
This has been discussed before and I think the best solution is probably to have a runtime resolution path as well as a compile time one, like the connection string.  

We could certainly have it try some obvious directories are relative paths first as well though, yes.

**Comment by Thorium** [comment]
Ok this seems to be already fixed in the GitHub repository version (I was again using the NuGet version).

**Comment by pezipink** [comment]
it is???

**Comment by Thorium** [comment]
I close this now and hope there will be Nuget package soon. :-)
But I also open some other bug with this GitHub version...
