### ISSUE TITLE
Postgres : Cannot delete record with pascalCaseId using .Delete() method

### ISSUE THREAD

**Issue by Dzoukr** [fsprojects/SQLProvider#275]
I have table XYZ (in Postgres) with two columns. First column called _pascalCaseId_ is primary key, second is just text.

Calling this code causes exception:

```
let rows = 
      query { 
          for x in Database.dataContext.MyContext.Configs do
          where (x.PascalCaseId=idToDelete)
          select x }
rows |> Seq.iter (fun x -> x.Delete())
Database.dataContext.SubmitUpdates()
```

with stack trace:

```
42703: column "pascalcaseid" does not exist
Npgsql.NpgsqlException (0x80004005): 42703: column "pascalcaseid" does not exist
   at Npgsql.NpgsqlConnector.DoReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage, Boolean isPrependedMessage)
   at Npgsql.NpgsqlConnector.ReadSingleMessage(DataRowLoadingMode dataRowLoadingMode, Boolean returnNullForAsyncMessage)
   at Npgsql.NpgsqlCommand.Execute(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteNonQueryInternal()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
```

It looks like problem with changing case for auto-generated strongly typed classes. When I change column to _pascalcaseid_ (everything in lowercase), it works ok. But having column starting on lowercase and containing some upper case seems to be the issue.

**Comment by ingted** [comment]
Hi Dzoukr, 

Excuse me, did you recompile your project after the database schema changed?

**Comment by Dzoukr** [comment]
Hi @ingted, yes I did. 

Now I am using undescores instead of pascal case and everything works ok, so it is not so big deal for me.
