### ISSUE TITLE
Could not load type 'System.Data.SqlClient.SqlConnection'

### ISSUE THREAD

**Issue by nojaf** [fsprojects/SQLProvider#462]
### Description

I'm trying out SQLProvider 1.1.14 with a netcore2.0 app. I get intellisense but it crashes at runtime. Building works.

### Repro steps

1. Create new netcoreapp2.0 F# project

2. Install SQLProvider 1.1.14

3. Create sql type with valid MS SQL connection

3. dotnet run

### Expected behavior

The type provider works at runtime and is able to query my database.

### Actual behavior

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'minimal_giraffe.App' threw an exception. ---> System.TypeInitializationException: The type initializer for '<StartupCode$minimal_giraffe>.$minimal_giraffe.App' threw an exception. --->
System.TypeLoadException: Could not load type 'System.Data.SqlClient.SqlConnection' from assembly 'System.Data.SqlClient, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at FSharp.Data.Sql.Providers.MSSqlServerProvider.FSharp-Data-Sql-Common-ISqlProvider-CreateConnection(String connectionString)
   at <StartupCode$FSharp-Data-SqlProvider>.$SqlRuntime.DataContext.-ctor@37-52.Invoke(String arg)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at FSharp.Data.Sql.Runtime.SqlDataContext..ctor(String typeName, String connectionString, DatabaseProviderTypes providerType, String resolutionPath, String[] referencedAssemblies, String runtimeAssembly, String owner, CaseSensitivityChange caseSensitivity, String t
ableNames, OdbcQuoteCharacter odbcquote, SQLiteLibrary sqliteLibrary, TransactionOptions transactionOptions, FSharpOption`1 commandTimeout)
   at <StartupCode$minimal_giraffe>.$minimal_giraffe.App..cctor() in C:\Temp\minimal-giraffe\Program.fs:line 27
   --- End of inner exception stack trace ---
   at minimal_giraffe.App..cctor()
   --- End of inner exception stack trace ---
   at minimal_giraffe.App.Main(String[] argv) in C:\Temp\minimal-giraffe\Program.fs:line 75
```
### Related information 

* Used database: MS SQL 2014
* Operating system: Windows 7
* .NET Runtime, CoreCLR or Mono Version: dotnet core 2.0

fsproj:

```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <DebugType>portable</DebugType>
    <AssemblyName>minimal_giraffe</AssemblyName>
    <OutputType>Exe</OutputType>
    <PackageId>minimal_giraffe</PackageId>
    <RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>
  <PropertyGroup>
    <IsWindows Condition="'$(OS)' == 'Windows_NT'">true</IsWindows>
    <IsOSX Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))' == 'true'">true</IsOSX>
    <IsLinux Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))' == 'true'">true</IsLinux>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsWindows)' == 'true'">
    <FscToolPath>C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0</FscToolPath>
    <FscToolExe>fsc.exe</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsOSX)' == 'true'">
    <FscToolPath>/Library/Frameworks/Mono.framework/Versions/Current/Commands</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsLinux)' == 'true'">
    <FscToolPath>/usr/bin</FscToolPath>
    <FscToolExe>fsharpc</FscToolExe>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="2.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="2.0.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="2.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.0.*" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.*" />
    <PackageReference Include="Giraffe" Version="0.1.0-beta-100" />
    <PackageReference Include="Giraffe.Razor" Version="0.1.0-beta-100" />
    <PackageReference Include="SQLProvider" Version="1.1.14" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.DotNet.Watcher.Tools" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Watch Include="**\*.cshtml" Exclude="bin\**\*" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Pages.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Views\*.cshtml;WebRoot\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
```

### Remark

I can't find System.Data.SqlClient 4.2.0 on [nuget](https://www.nuget.org/packages/System.Data.SqlClient/), am I missing some sort of assembly redirect?

**Comment by Thorium** [comment]
Yes, you need the dll to be present. The location is under runtime folder, e.g. `System.Data.SqlClient\runtimes\win\lib\netstandard2.0\` See the post-build-task in sample project from https://github.com/fsprojects/SQLProvider/blob/master/tests/SqlProvider.Core.Tests/MsSql/SqlProvider.Core.Tests.fsproj

**Comment by nojaf** [comment]
Thanks @Thorium

**Comment by pizycki** [comment]
Hit the same issue. I was trying to use SQL Provider in C# Console app (Core 3.1). Installing [System.Data.SqlClient package](https://www.nuget.org/packages/System.Data.SqlClient) did the trick for me.

**Comment by Volen99** [comment]
> Hit the same issue. I was trying to use SQL Provider in C# Console app (Core 3.1). Installing [System.Data.SqlClient package](https://www.nuget.org/packages/System.Data.SqlClient) in C# project did the trick for me.

You are a life saver, bro!! 🔥
